urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin
from main.views_add import test


admin.autodiscover()
#handler404 = 'main.views.page_not_found2'
urlpatterns = patterns('main.views',
    url(r'^adm475/', include(admin.site.urls)),
    url(r'^$', 'check_code'),
    url(r'^coming_soon/$', 'coming_soon'),
#    url(r'^closed/$', 'registration_closed'),
    url(r'^check_code/$', 'check_code'),
    url(r'^attendance/(?P<code>\d{5})/$', 'attendance'),
    url(r'^attendance/(?P<code>\d{5})/(?P<status>\w{1})/$', 'status'),
#    url(r'^attendance/newdate/$', 'new_date'),
#    url(r'^attendance/celeb/$', 'celeb'),
    url(r'^attendance/guest/$', 'others'),
#    url(r'^attendance/prizers/$', 'prizers'),
    url(r'^send_mail/(?P<show>\w+)/$', 'send_mail'),
    url(r'^test/$', test),
    url(r'^test.txt/$', test),
#    url(r'^attendance/tguest/$', 'taras'),
#    url(r'^attendance/tguest/addr/$', 'taras_addr'),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

main/models.py
# -*- coding: utf-8 -*- 
#import django django.VERSION
from django.db import models
from django import forms
from django.http import Http404
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator,MinValueValidator
#from django.utils import translation
from django.utils.translation import ugettext
from django.utils.translation import ugettext_lazy as _

SEX_CHOICES = (
   ('F', _('Female')),
   ('M', _('Male')),
)

I_DELIVERY_CHOICES = (
    ('SLF', _('Pass personally')),
    ('COUR', _('Via courier')),
    ('INTL',_('International mailing')),
    ('SNDT', _('Send just ticket')),
)

I_TYPE_CHOICES = (
    ('I', _('Invitation')),
    ('T', _('Tickets')),
)


T_DELIVERY_CHOICES = (
    ('SLF', _('Pass personally')),
    ('COUR', _('Via courier')),
    ('INTL',_('International mailing')),
)

TW_DELIVERY_CHOICES = (
    ('SLF', _('Take personally')),
    ('COUR', _('Via courier')),
)

CATEGORY_CHOICES = (
    ('NORM', _('Common')),
    ('VIP P', _('VIP Partner')),
    ('VIP G', _('VIP Goverment')),
    ('CELEB', _('Celebrity')),
    ('GOV', _('Goverment')),
    ('STAGE', _('Stage Staff')),
#    ('BART', _('Barter')),
    ('JORN', _('Jornalists')),
#    ('DISNEY', _('Disney')),
#    ('PRIZE',_('Prize-winner')),
#    ('TARAS', _('Tarasova')),
)

PARKING_CHOICES = (
    ('-', _('No matter')),
    ('Y', _('Yes')),
    ('N', _('No')),
)

STATUS_CHOICES = (
    ('R', _('Rejected')),
    ('C', _('Confirmed')),
    ('D', _('Another date')),
)

# I.Verba 02.09.14 Changed to Show class (look at Entity in admin-page)

#SHOW_CHOICES = (
#    ('WOZ',_('The Wizard of Oz')),
#    ('CHG',_('CHICAGO')),
#    ('TLM', _('The Little Mermaid')),
#    ('MM', _('Mamma mia!')),
#    ('TTM',_('The Three Musketeers')),
#    ('AMM', _('ACTION on Mamma mia!')),
#    ('POTO', _('Phantom of The Opera')),
#    ('BATB', _('Beauty and The Beast')),
#    
#)

ENTRANCE_CHOICES = (
    ('N', _('Normal')),
    ('V', _('VIP')),
)

REG_CHOICES  = (
    ('N', _('not opened yet')),
    ('O', _('opened')),
    ('S', _('temporarily suspended')),
    ('C', _('closed already')),	
)


class Show(models.Model):
    show = models.CharField(_('Event code'), primary_key=True , max_length=16, null=False, blank=False)
    name = models.CharField(_('Event name'),max_length=128, null=False, blank=False)
    eng_name = models.CharField(_('International name of Event'), max_length=128, null=True, blank=True)
    event_time = models.DateTimeField(_('Event date&time'), null=False, blank=False)
    doors_open = models.TimeField(_('Doors open at'), null=True, blank=True)	
    venue = models.CharField(_('Venue (where?)'),max_length=128, null=False, blank=False)
    eng_venue = models.CharField(_('International name of Venue (where?)'), max_length=128, null=True, blank=True)
    address = models.CharField(_('Event address'),max_length=256, null=False, blank=False)
    eng_address = models.CharField(_('International address of Event'),max_length=256, null=True, blank=True)	
    send_mail = models.BooleanField(_('Send email to guests as result of registration'),default=True,null=False, blank=False)
    reg_status = models.CharField(_('Registration status'),max_length=1, null=False, blank=False, choices=REG_CHOICES,default='N')
	
    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')
        ordering = ('-event_time','name')
#        unique_together = ('show','language',)
 
    def __unicode__(self):
        return u'%s' % self.name


class Invitation(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    post_date = models.DateTimeField(_('Post date'),auto_now_add=True)
    code = models.CharField(_('Invitation code'),max_length=5, unique=True)
    language = models.CharField(_('Language'),max_length=2, choices=settings.LANGUAGES, default='ru')
    category = models.CharField(_('Guest category'),max_length=16, choices=CATEGORY_CHOICES)
    l_name = models.CharField(_('Last name'),max_length=128)
    f_name = models.CharField(_('First name'),max_length=128)
    s_name = models.CharField(_('Middle name'),max_length=128, null=True, blank=True)
    sex = models.CharField(_('Sex'), max_length=1, choices=SEX_CHOICES)
    company = models.CharField(_('Company'),max_length=256)
    position = models.CharField(_('Position'),max_length=256)
    contact_phone = models.CharField(_('Contact phone'),max_length=64)
    mobile_phone = models.CharField(_('Mobile phone'),max_length=64)
    assistant_person = models.CharField(_('Assistant person'),max_length=128, null=True, blank=True)
    i_delivery_mode = models.CharField(_('Invitation delivery mode'),max_length=16, choices=I_DELIVERY_CHOICES)
    t_delivery_mode = models.CharField(_('Ticket delivery mode'),max_length=16, choices=T_DELIVERY_CHOICES)
    address = models.TextField(_('Address'),null=True, blank=True)
    status = models.CharField(_('Status'),max_length=128, null=True, blank=True)
    add_info = models.TextField(_('Additional information'),null=True, blank=True)
    estimated_num = models.SmallIntegerField(_('Estimated number of guests'),default=2)
    parking_place = models.CharField(_('Need a parking place'),max_length=1, choices=PARKING_CHOICES)
    sent = models.BooleanField(_('Invitation sent'),default=False)
    sent_date = models.DateTimeField(_('Sent date'), null=True, blank=True)
    show = models.ForeignKey(Show, verbose_name=_('Event'), db_index=False, db_column='show', null=False, blank=False)
    confirmed = models.BooleanField(_('Responce received'),default=False)
    comment = models.TextField(_('Comments'),null=True, blank=True)
    is_typographical=models.BooleanField(_('Typographical personalisation'),default=False)
    inv_type = models.CharField(_('Invitation type'),max_length=1, choices=I_TYPE_CHOICES, default='I')
    entrance = models.CharField(_('Entrance'),max_length=1, choices=ENTRANCE_CHOICES, default='N')

	
    class Meta:
        verbose_name = _('invitation')
        verbose_name_plural = _('invitations')
        ordering = ('-post_date',)

    def __unicode__(self):
        return u'%s %s (%s)' % (self.l_name, self.f_name, self.code)
		
class Confirmation(models.Model):
    invitation = models.OneToOneField(Invitation, verbose_name=_('invitation'))
    post_date = models.DateTimeField(_('Post date'),auto_now_add=True)
    l_name = models.CharField(_('Last name'),max_length=128, null=True, blank=True)
    f_name = models.CharField(_('First name'),max_length=128, null=True, blank=True)
    s_name = models.CharField(_('Middle name'),max_length=128, null=True, blank=True)
    company = models.CharField(_('Company'),max_length=256, null=True, blank=True)
    position = models.CharField(_('Position'),max_length=256, null=True, blank=True)
    contact_phone = models.CharField(_('Contact phone'),max_length=64, null=True, blank=True)
    email = models.EmailField(_('Email'), max_length=128, null=True, blank=True)
    address = models.TextField(_('Address'),null=True, blank=True)
    assistant_person = models.CharField(_('Assistant person'),max_length=128, null=True, blank=True)
    places_num = models.SmallIntegerField(_('Number of seats'), null=True, blank=True)
    comment = models.TextField(_('Comments'), null=True, blank=True)
    status = models.CharField(_('Status'),max_length=1, choices=STATUS_CHOICES)
    sent = models.BooleanField(_('Tickets sent'),default=False)
    sent_date = models.DateTimeField(_('Sent date'), null=True, blank=True)
    parking_allocated = models.BooleanField(_('Parking allocated'),default=False, null=False)
    card_sent=models.BooleanField(_('Card sent'),default=False,null=False)
    card_sent_date = models.DateTimeField(_('Card sent date'), null=True, blank=True)
    lounge=models.BooleanField(_('Lounge'),default=False,null=False)
    places_category=models.SmallIntegerField(_('Places category'), null=True, blank=True, validators=[MinValueValidator(1),MaxValueValidator(5),])
    places_allocated=models.BooleanField(_('Places_allocated'),default=False,null=False)
    mail_sent_date = models.DateTimeField(_('Mail sent date&time'), null=True, blank=True)
	
    class Meta:
        verbose_name = _('confirmation')
        verbose_name_plural = _('confirmations')
        ordering = ('-post_date',)

    def get_tix(self):
        return self.ticket_set.all().count()
    get_tix.short_description = _('Tickets issued')

    def get_parking_requested(self):
        return self.invitation.parking_place
    get_parking_requested.short_description = _('Need a parking place')

    def get_show(self):
        return self.invitation.show
    get_show.short_description = _('Event')

    def create_confirmation(self):
        inv=self
        if inv.confirmed==False:
            con = Confirmation()
            con.invitation = inv
            inv.confirmed=True
            con.status='C'
            con.f_name = inv.f_name 
            con.l_name = inv.l_name 
            con.s_name = inv.s_name 
            con.contact_phone = inv.contact_phone
            con.assistant_person = inv.assistant_person
            con.address = inv.address
            con.places_num = inv.estimated_num
            con.comment = inv.add_info
            con.company = inv.company
            con.position = inv.position
#            try:
#                con.save()
#            except:
#               raise Http404

#            inv.save()

    def __unicode__(self):
        return u'%s %s (%s)' % (self.invitation.l_name, self.invitation.f_name, self.invitation.code)

class Section(models.Model):
    name = models.CharField(_('Section name'),max_length=128)

    class Meta:
        verbose_name = _('section')
        verbose_name_plural = _('sections')
        ordering = ('name',)

    def __unicode__(self):
        return u'%s' % self.name

class Ticket(models.Model):

templates/attendance.html
{% extends "base.html" %}
{% load i18n %}{% get_current_language as LANGUAGE_CODE %}
{% block content %}

<p>
{% include "greeting.html" %} 
</p>
<p>
{% if inv.language == 'ru' %}
 Планируете ли Вы посетить премьеру ледового арена-шоу<br/>
  «{{ inv.show.name }}» {{ inv.show.event_time.date }}?
{% else %}
 Please confirm your attendance to the Gala Opening Night of <br/>
 «{{ inv.show.eng_name|default:inv.show.name }}» on {% include "eventtime_eng.html" %}
{% endif %} 

</p>
<br/>
<a href="{% url main.views.status code=inv.code status='C' %}">{% if inv.language == 'en' %}I confirm that I am able to attend {% else %}{% trans 'I confirm that I will attend' %} {% endif %}</a><br/><br/>
<a href="{% url main.views.status code=inv.code status='R' %}">{% if inv.language == 'en' %}Unfortunately, {% endif %}{% trans 'I am unable to attend' %}</a><br/><br/>


{% endblock %}

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Attendance confirmation / Регистрация гостей</title>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,600,700&subset=latin,cyrillic" rel="stylesheet" type="text/css" />
<link rel="shortcut icon" href="/static/images/favicon.ico" />

<script src="/static/js/jquery.js"></script>
<script>
    function swapImages() {
        var $active = $('#logo .active');
        var $next = ($('#logo .active').next().length > 0) ? $('#logo .active').next() : $('#logo img:first');
        $active.removeClass('active');
        $next.addClass('active');
    }

    $(document).ready( function() {
        setInterval('swapImages()', 4000);
    })
</script>
<style type="text/css">
<!--
body {
	background:#FFFFFF;
	xbackground:url(/static/images/bg_new.jpg) top center no-repeat #0A1543;
	xbackground-color: #001C75;
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;

}
.divMain {
	xwidth: 1000px;
	margin-right: auto;
	margin-left: auto;
	xbackground-image: url(/static/images/grad.jpg);
	background-repeat: repeat-x;
	padding-bottom: 20px;
}
.divHead {height:400px;background:url(/static/images/bg_header.jpg) center center no-repeat #000033;
	background-size:cover;
	-moz-background-size:cover;
	-webkit-background-size:cover;
	-o-background-size:cover;
}
.divLogo {
	text-align: center;
	margin-top: -400px;
    width: 900px;
    margin-right: auto;
	margin-left: auto;
}
.divLogo img {
    display:none;
}
.divLogo img.active {
    display:block;
}
.divContent {
	width: 875px;
	margin-left: auto;
	margin-right: auto;
	xbackground-color: #FFF;
	color:#000000;
	padding: 40px;
	text-align: center;
	margin-top:0px;
}
body,td,th {
	font-family: "Open Sans", Lucida Sans Unicode, Lucida Grande, sans-serif;
}

a, a:active,a:visited,a:hover {color:#0c2b6a;}

.formTable {
	font-size: 18px;
}
.formTable tr {
    xbackground-color: #6CF;
}
.formTable th {
	text-align:left;
	font-weight: normal;
}
.formTable th.fieldRequired {
	text-align:left;
	font-weight: bold;
}
.formTable input {
    font-family: "Open Sans", Lucida Sans Unicode, Lucida Grande, sans-serif;
    border: 1px solid #021b44;
	width: 300px;
	padding: 4px;
}
.formTable select {
    font-family: "Open Sans", Lucida Sans Unicode, Lucida Grande, sans-serif;
    border: 1px solid #021b44;
	width: 300px;
	padding: 4px;
}
.formTable textarea {
    font-family: "Open Sans", Lucida Sans Unicode, Lucida Grande, sans-serif;
    border: 1px solid #021b44;
	width: 300px;
	padding: 4px;
}
.formTable input.fieldError {
    background-color: #FCC;
}
.formNumInput {
	border: 1px solid #0c2b6a;
    font-family: "Open Sans", Lucida Sans Unicode, Lucida Grande, sans-serif;
	font-size: 36px;
	font-weight: bold;
	padding: 4px;
	text-align: center;
	background-color: #ffffff;
}
.formButton {
	font-size:110%;
	font-weight: bold;
	color: #ffffff;
	background-color: #e81d2d;
	border: 0px solid #021b44;
    padding: 8px
}
.error {
	padding: 2px;
	width: 500px;
	margin-right: auto;
	margin-left: auto;
	border: thick double #FAA620;
	color: #FAA620;
}
-->
</style></head>

<body bgcolor="#f7eb21">
  
<div class="divMain">
  <div class="divHead"></div>
  <div id="logo" class="divLogo">
    <img src="/static/images/sblogo-en_new.png" width="900" height="396" />
    <img src="/static/images/sblogo-ru_new.png" width="900" height="396" class="active" />
  </div>
  <div class="divContent">
{% block content%}{% endblock %}
  </div>
</div>
</body>
</html>

templates/greeting.html
{% load i18n %}{% get_current_language as LANGUAGE_CODE %}{% if inv.sex == 'M' %}{% trans 'Dear Mr' %}{% else %}{% trans 'Dear Mrs' %}{% endif %} {% if inv.language == 'en' %}{{ inv.l_name }}{% else %}{% if inv.s_name and inv.s_name != '' and inv.s_name != ' ' and inv.s_name != '-' %}{{ inv.f_name }} {{ inv.s_name }}{% else %}{{ inv.f_name }}{% endif %}{% endif %},

templates/registration_closed.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}

{% with s=inv.show %}
<p>
{% if inv.language = 'ru' %}	
Регистрация на мероприятие «{{ s.name }}» {{ s.event_time.date }} {{ s.get_reg_status_display }}.
{% else %}
Registration for the event "{{ s.eng_name|default:s.name }}" on {{s.event_time.date}} is {{ s.get_reg_status_display }}.
{% endif %} 
</p>
<p>
{% trans 'If you have any questions please contact our Opening night Manager' %} <br/>
{% trans 'by calling +7 903 578 01 12' %}</p>



{% endwith%}

{% endblock %}

templates/status-celeb.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

{% if form.errors %}
<div class="error">
  <ul>
  {% for error in form.non_field_errors %}
     <li><strong>{{ error|escape }}</strong></li>
  {% endfor %}
  {% for field in form %}
    {% if field.errors %}<li><strong>'{{ field.label }}'</strong>: {{ field.errors|striptags }}</li>{% endif %}
  {% endfor %}
  </ul>
</div>
{% endif %}

<form action="{% url main.views.celeb %}" method="post">{% csrf_token %}
<table align="center" class="formTable" cellspacing="1" cellpadding="3">

<tr><th{% if form.l_name.field.required %} class="fieldRequired"{% endif %}><label for="id_l_name">{{ form.l_name.label }}:</label></th><td>{{ form.l_name }}</td></tr>
<tr><th{% if form.f_name.field.required %} class="fieldRequired"{% endif %}><label for="id_f_name">{{ form.f_name.label }}:</label></th><td>{{ form.f_name }}</td></tr>
<tr><th{% if form.s_name.field.required %} class="fieldRequired"{% endif %}><label for="id_s_name">{{ form.s_name.label }}:</label></th><td>{{ form.s_name }}</td></tr>
<tr><th{% if form.contact_phone.field.required %} class="fieldRequired"{% endif %}><label for="id_contact_phone">{{ form.contact_phone.label }}:</label></th><td>{{ form.contact_phone }}</td></tr>
<tr><th{% if form.assistant_person.field.required %} class="fieldRequired"{% endif %}><label for="id_assistant_person">{{ form.assistant_person.label }}:</label></th><td>{{ form.assistant_person }}</td></tr>
<tr><th{% if form.email.field.required %} class="fieldRequired"{% endif %}><label for="id_email">{{ form.email.label }}:</label></th><td>{{ form.email }}</td></tr>
<tr><th{% if form.tix_num.field.required %} class="fieldRequired"{% endif %}><label for="id_tix_num">{{ form.tix_num.label }}:</label></th><td>{{ form.tix_num }}</td></tr>
<tr><th{% if form.add_info.field.required %} class="fieldRequired"{% endif %}><label for="id_add_info">{{ form.add_info.label }}:</label></th><td>{{ form.add_info }}</td></tr>

</table><br/>
<input type="submit" class="formButton" value="{% trans 'Submit' %}"/>
</form>

{% endblock %}

templates/status-others.html
{% extends "base.html" %}
{% load i18n %}{% get_current_language as LANGUAGE_CODE %}
{% block content %}

{% if form.errors %}
<div class="error">
  <ul>
  {% for error in form.non_field_errors %}
     <li><strong>{{ error|escape }}</strong></li>
  {% endfor %}
  {% for field in form %}
    {% if field.errors %}<li><strong>'{{ field.label }}'</strong>: {{ field.errors|striptags }}</li>{% endif %}
  {% endfor %}
  </ul>
</div>
{% endif %}
<body onload="document.getElementById('id_email').focus()">
<form action="{% url main.views.others %}" method="post">{% csrf_token %}
<table align="center" class="formTable" cellspacing="1" cellpadding="3">
{% if inv.language == 'ru' %}
 Пожалуйста, подтвердите контактную информацию:
{% else %}
 Please confirm your contact details:
{% endif %} 

<tr><th{% if form.l_name.field.required %} class="fieldRequired"{% endif %}><label for="id_l_name">{{ form.l_name.label }}:</label></th><td>{{ form.l_name }}</td></tr>
<tr><th{% if form.f_name.field.required %} class="fieldRequired"{% endif %}><label for="id_f_name">{{ form.f_name.label }}:</label></th><td>{{ form.f_name }}</td></tr>

{% if inv.language == 'ru' %}
<tr><th{% if form.s_name.field.required %} class="fieldRequired"{% endif %}><label for="id_s_name">{{ form.s_name.label }}:</label></th><td>{{ form.s_name }}</td></tr>
{% endif %}

<tr><th{% if form.contact_phone.field.required %} class="fieldRequired"{% endif %}><label for="id_contact_phone">
	{% if inv.language == 'ru' %}Контактный телефон:{% else %}Contact telephone number:{% endif %}
	</label></th><td>{{ form.contact_phone }}</td></tr>

<tr><th{% if form.assistant_person.field.required %} class="fieldRequired"{% endif %}><label for="id_assistant_person">
	{% if inv.language == 'ru' %}Контактное лицо, если это не Вы:
	{% else %}Contact name, if different from above:
	{% endif %}
	</label></th><td>{{ form.assistant_person }}</td></tr>

<tr><th{% if form.email.field.required %} class="fieldRequired"{% endif %}><label for="id_email">
	{% if inv.language == 'ru' %} 
		Электронный адрес, на который мы отправим Вам копию подтверждения регистрации:
	{% else %} 
		Email address for receipt of confirmation:
	{% endif %}
	</label></th><td>{{ form.email }}</td></tr>

{% if form.tix_num %}
<tr><th{% if form.tix_num.field.required %} class="fieldRequired"{% endif %}><label for="id_tix_num">{{ form.tix_num.label }}:</label></th><td>{{ form.tix_num }}</td></tr>
{% endif %}

{% if form.address %}
    <tr><th{% if form.address.field.required %} class="fieldRequired"{% endif %}><label for="id_address">
	{% if inv.language == 'ru' %}
		Фактический адрес и контактные данные для доставки билетов
	{% else %}
		The address to receive your tickets 
	{% endif %}
	:</label></th><td>{{ form.address }}</td></tr>
{% endif %}

{% if form.is_temp_addr %}
    <tr><th{% if form.is_temp_addr.field.required %} class="fieldRequired"{% endif %}><label for="id_is_temp_addr">{{ form.is_temp_addr.label }}:</label></th><td>{{ form.is_temp_addr }}</td></tr>
{% endif %}

</table><br/>

<input type="submit" class="formButton" value="{% trans 'Submit' %}"/>
<p>
{% if inv.language == 'ru' %}
В случае возникновения вопросов по заполнению формы <br/>
обращайтесь к менеджеру премьеры по телефону: +7 903 578 01 12
{% else %}
Should you have any questions regarding answering this form<br/>
please contact our opening night manager by calling +7 903 578 01 12
{% endif %}
</form>

{% endblock %}

templates/status-others_done.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
{% include "status-others_done_base.html" %}
{% endblock %}

templates/status-taras-addr.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

{% if form.errors %}
<div class="error">
  <ul>
  {% for error in form.non_field_errors %}
     <li><strong>{{ error|escape }}</strong></li>
  {% endfor %}
  {% for field in form %}
    {% if field.errors %}<li><strong>'{{ field.label }}'</strong>: {{ field.errors|striptags }}</li>{% endif %}
  {% endfor %}
  </ul>
</div>
{% endif %}

<form action="{% url main.views.taras_addr %}" method="post">{% csrf_token %}
<table align="center" class="formTable" cellspacing="1" cellpadding="3">

<tr><th{% if form.address.field.required %} class="fieldRequired"{% endif %}><label for="id_address">{{ form.address.label }}:</label></th><td>{{ form.address }}</td></tr>

</table><br/>
<input type="submit" class="formButton" value="{% trans 'Submit' %}"/>
</form>

{% endblock %}

templates/status-taras.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

{% if form.errors %}
<div class="error">
  <ul>
  {% for error in form.non_field_errors %}
     <li><strong>{{ error|escape }}</strong></li>
  {% endfor %}
  {% for field in form %}
    {% if field.errors %}<li><strong>'{{ field.label }}'</strong>: {{ field.errors|striptags }}</li>{% endif %}
  {% endfor %}
  </ul>
</div>
{% endif %}

<form action="{% url main.views.taras %}" method="post">{% csrf_token %}
<table align="center" class="formTable" cellspacing="1" cellpadding="3">

<tr><th{% if form.l_name.field.required %} class="fieldRequired"{% endif %}><label for="id_l_name">{{ form.l_name.label }}:</label></th><td>{{ form.l_name }}</td></tr>
<tr><th{% if form.f_name.field.required %} class="fieldRequired"{% endif %}><label for="id_f_name">{{ form.f_name.label }}:</label></th><td>{{ form.f_name }}</td></tr>
<tr><th{% if form.s_name.field.required %} class="fieldRequired"{% endif %}><label for="id_s_name">{{ form.s_name.label }}:</label></th><td>{{ form.s_name }}</td></tr>
<tr><th{% if form.contact_phone.field.required %} class="fieldRequired"{% endif %}><label for="id_contact_phone">{{ form.contact_phone.label }}:</label></th><td>{{ form.contact_phone }}</td></tr>
<tr><th{% if form.email.field.required %} class="fieldRequired"{% endif %}><label for="id_email">{{ form.email.label }}:</label></th><td>{{ form.email }}</td></tr>
<tr><th{% if form.tix_num.field.required %} class="fieldRequired"{% endif %}><label for="id_tix_num">{{ form.tix_num.label }}:</label></th><td>{{ form.tix_num }}</td></tr>
<tr><th{% if form.t_delivery_mode.field.required %} class="fieldRequired"{% endif %}><label for="id_t_delivery_mode">{{ form.t_delivery_mode.label }}:</label></th><td>{{ form.t_delivery_mode }}</td></tr>
<tr><th{% if form.add_info.field.required %} class="fieldRequired"{% endif %}><label for="id_add_info">{{ form.add_info.label }}:</label></th><td>{{ form.add_info }}</td></tr>

</table><br/>
<input type="submit" class="formButton" value="{% trans 'Submit' %}"/>
</form>

{% endblock %}